# You can use any Docker image from Docker Hub or your own container registry
image: openjdk:8-jdk
  
pipelines:
  default:
    - step:
        script:  # Modify the commands below to build and test your repository.
          - ./gradlew --version
          - ./gradlew check test assemble