# You can use any Docker image from Docker Hub or your own container registry
image: jimschubert/8-jdk-alpine-mvn:1.0
  
pipelines:
  default:
    - step:
        script:  # Modify the commands below to build and test your repository.
          - ./gradlew --version
          - ./gradlew check test assemble